# Create a new user
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "name": "us48",
  "email": "use48@new.local",
  "password": "1235fdb",
  "avatar": "avatar48.jpg",
  "gender": "мужской",
  "dateOfBirth": "2004-04-03",
  "description": "Keks35efefeferf",
  "location": "Удельная",
  "backgroundImg": "bf48.png"
}

###

# Get user by ID
GET http://localhost:3000/api/user/67d321a265c52bcc5be7ece6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2QzMjFhMjY1YzUyYmNjNWJlN2VjZTYiLCJlbWFpbCI6InVzZTQ4QG5ldy5sb2NhbCIsIm5hbWUiOiJ1czQ4IiwiaWF0IjoxNzQxODkwNDMwLCJleHAiOjE3NDE4OTA3MzB9.SnZQd1gnhwe8XAAm3gkvMthIqKDAx6jI6hDvnZBao-g

###

# Login user by email and password
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "use48@new.local",
  "password": "1235fdb"
}

###
