# Create a new user
POST http://localhost:3333/api/user/register HTTP/1.1
Content-Type: application/json

{
  "name": "us61",
  "email": "use61@new.local",
  "password": "1254567890",
  "avatar": "avatar61.jpg",
  "dateOfBirth": "2004-05-31",
  "location": "Пионерская",
  "gender": "неважно",
  "role": "user"
}

###

# Get user by ID
GET http://localhost:3333/api/user/68069b3237a1d42f203fbcac HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODA2OWIzMjM3YTFkNDJmMjAzZmJjYWMiLCJuYW1lIjoidXM2MCIsImVtYWlsIjoidXNlNjBAbmV3LmxvY2FsIiwiYXZhdGFyIjoiYXZhdGFyNjAuanBnIiwiZGF0ZU9mQmlydGgiOiIyMDA0LTA0LTI5VDE4OjAwOjAwLjAwMFoiLCJsb2NhdGlvbiI6ItCf0LjQvtC90LXRgNGB0LrQsNGPIiwiZ2VuZGVyIjoi0L3QtdCy0LDQttC90L4iLCJyb2xlIjoiY29hY2giLCJjcmVhdGVkQXQiOiIyMDI1LTA0LTIxVDE5OjIzOjMwLjUyOFoiLCJiYWNrZ3JvdW5kSW1nIjoiZGVmYXVsdC5wbmciLCJpYXQiOjE3NDU3ODE0ODIsImV4cCI6MTc0NTc4MjM4Mn0.wL5smvKCsJ5vK9HBXLLG1DKgnERZAUKd3HIeAuHezT0

###

# Login user by email and password
POST http://localhost:3333/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "use60@new.local",
  "password": "1254567890"
}

###

# Get new JWT pair
POST http://localhost:3333/api/user/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RkYjJjYWQ0MDI0NjM1ZmNjMDZhNjUiLCJuYW1lIjoidXM1MyIsImVtYWlsIjoidXNlNTNAbmV3LmxvY2FsIiwiYXZhdGFyIjoiYXZhdGFyNTMuanBnIiwiZ2VuZGVyIjoi0LbQtdC90YHQutC40LkiLCJkYXRlT2ZCaXJ0aCI6IjIwMDQtMDQtMDRUMTg6MDA6MDAuMDAwWiIsImRlc2NyaXB0aW9uIjoiR2lybDUzIHJ0Z3J0ZyB0Z2FyeXl0aCB0cnIiLCJsb2NhdGlvbiI6ItCj0LTQtdC70YzQvdCw0Y8iLCJiYWNrZ3JvdW5kSW1nIjoiYmY1M3BuZyIsImNyZWF0ZWRBdCI6IjIwMjUtMDMtMjFUMTg6NDE6MTQuNDA3WiIsInRva2VuSWQiOiI3NzUyNDJiMS1hOGU5LTQzZTktYjZjZi05Y2QyNzM0ZjVlMjUiLCJpYXQiOjE3NDQ3MzkxNTAsImV4cCI6MTc0NTM0Mzk1MH0.2K4edXmZYlYdyVIab2GvLn59qi7aKxRkBTpuQsknCcU

###


# Check user token
POST http://localhost:3333/api/user/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODA3YjUzN2ViYzcwNjBjOTRjYzczZDUiLCJuYW1lIjoidXM2MSIsImVtYWlsIjoidXNlNjFAbmV3LmxvY2FsIiwiYXZhdGFyIjoiYXZhdGFyNjEuanBnIiwiZGF0ZU9mQmlydGgiOiIyMDA0LTA1LTMwVDE4OjAwOjAwLjAwMFoiLCJsb2NhdGlvbiI6ItCf0LjQvtC90LXRgNGB0LrQsNGPIiwiZ2VuZGVyIjoi0L3QtdCy0LDQttC90L4iLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjUtMDQtMjJUMTU6MjY6NDcuNDQ4WiIsImJhY2tncm91bmRJbWciOiJkZWZhdWx0LnBuZyIsImlhdCI6MTc0NTMzNTYwNywiZXhwIjoxNzQ1MzM2NTA3fQ.EuJb8hUqCqMjcxUZTFsKcKZmls8CWusY9HnUzdZMAys

###
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2RkYjJjYWQ0MDI0NjM1ZmNjMDZhNjUiLCJuYW1lIjoidXM1MyIsImVtYWlsIjoidXNlNTNAbmV3LmxvY2FsIiwiYXZhdGFyIjoiYXZhdGFyNTMuanBnIiwiZ2VuZGVyIjoi0LbQtdC90YHQutC40LkiLCJkYXRlT2ZCaXJ0aCI6IjIwMDQtMDQtMDRUMTg6MDA6MDAuMDAwWiIsImRlc2NyaXB0aW9uIjoiR2lybDUzIHJ0Z3J0ZyB0Z2FyeXl0aCB0cnIiLCJsb2NhdGlvbiI6ItCj0LTQtdC70YzQvdCw0Y8iLCJiYWNrZ3JvdW5kSW1nIjoiYmY1M3BuZyIsImNyZWF0ZWRBdCI6IjIwMjUtMDMtMjFUMTg6NDE6MTQuNDA3WiIsInRva2VuSWQiOiJmMjE0Yjc0NC1iZTAyLTQ3NmQtYjcxZS0wNjljN2VmNmIwMzYiLCJpYXQiOjE3NDQ4MjcyODksImV4cCI6MTc0NTQzMjA4OX0.1lPjQ8Av0CA5rU1jUxTvmZTEsoMY3czIvoFKBolWwBM
