# Create a new training
POST http://localhost:3000/api/training/create HTTP/1.1
Content-Type: application/json

{
  "title": "training3",
  "backgroungImg": "bf48.png",
  "level": "новичок",
  "type": "йога",
  "duration": "10-30 мин",
  "price": 150,
  "calories": 1001,
  "description": "йога, индивидуальный подход",
  "gender": "для женщин",
  "video": "bf48.mp4",
  "rating": 0,
  "coach": "SuperCoach",
  "specialOffer": false
}

###

# Get array of trainings

###

# Get user by ID
GET http://localhost:3000/api/user/67d321a265c52bcc5be7ece6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2QzMjFhMjY1YzUyYmNjNWJlN2VjZTYiLCJlbWFpbCI6InVzZTQ4QG5ldy5sb2NhbCIsIm5hbWUiOiJ1czQ4IiwiaWF0IjoxNzQxODkwNDMwLCJleHAiOjE3NDE4OTA3MzB9.SnZQd1gnhwe8XAAm3gkvMthIqKDAx6jI6hDvnZBao-g

###
