# Create a new training
POST http://localhost:3000/api/training/create HTTP/1.1
Content-Type: application/json

{
  "title": "training6",
  "backgroungImg": "bg06.png",
  "level": "профессионал",
  "type": "кроссфит",
  "duration": "50-80 мин",
  "price": 1350,
  "calories": 2500,
  "description": "кроссфит бла-бла-бла",
  "gender": "для всех",
  "video": "video0006.mp4",
  "rating": 5,
  "coach": "SuperCoach6",
  "specialOffer": true
}

###

# Get array of trainings
GET http://localhost:3000/api/training

###

# Get training by ID
GET http://localhost:3000/api/training/67dabe1fa27d92116d5e2735

###
