# Create a new training
POST http://localhost:3000/api/training/create HTTP/1.1
Content-Type: application/json

{
  "title": "training12",
  "backgroungImg": "bg012.png",
  "level": "новичок",
  "type": "пилатес",
  "duration": "10-30 мин",
  "price": 1000,
  "calories": 1200,
  "description": "тянись далеко",
  "gender": "для женщин",
  "video": "video00012.mp4",
  "coach": "Superавамвм",
  "specialOffer": false
}

###

# Get training by ID
GET http://localhost:3000/api/training/67dc5e5f529ae73a51ceb854

###

# Delete training
DELETE http://localhost:3000/api/training/67dc60790e227ff19e1d522d

###

# Update training
PATCH http://localhost:3000/api/training/67dc60790e227ff19e1d522d
Content-Type: application/json

{
  "rating": [0, 5, 4, 5, 5]
}

###

# Get training list
GET http://localhost:3000/api/training

###
